telegram_token: "8199318566:AAEZ3auerXi8sxc48FjTUwW8q9-5YJQOzqo"
template_path: "/etc/telegrambot/template.tmpl"
time_zone: "Asia/Ho_Chi_Minh"
split_token: "|"
time_outdata: "02/01/2006 15:04:05"
split_msg_byte: 10000