global:
  resolve_timeout: 1m

receivers:

# Group Dự phòng
- name: systems-team-telegram
  webhook_configs:
  - url: 'http://bravo-monitoring-alertbot.bravo-monitoring.svc.cluster.local:9087/alert/-4194274582'


route:
  continue: false
  group_by: ['instance']
  group_interval: 1m
  group_wait: 5s
  repeat_interval: 1m
  receiver: systems-team-telegram
  routes:

##################### SERVER-NODE EXPORTER #######################
    # ClusterManager
    - match:
        app_type: Cluster Manager
        category: server  
      receiver: systems-team-telegram
      group_wait: 10s

##################### SERVER-NODE RAM #######################
    - match:
        app_type: Cluster Manager
        category: memory  
      receiver: systems-team-telegram
      group_wait: 10s
##################### SERVER-NODE RAM #######################
    - match:
        app_type: Cluster Manager
        category: disk  
      receiver: systems-team-telegram
      group_wait: 10s