global:
  resolve_timeout: 1m

receivers:

- name: system-kubernetes
  webhook_configs:
  - url: 'http://bravo-monitoring-alertbot-k8s.bravo-monitoring.svc.cluster.local:9087/alert/-4570531790'

- name: service-kubernetes
  webhook_configs:
  - url: 'http://bravo-monitoring-alertbot-k8s.bravo-monitoring.svc.cluster.local:9087/alert/-4579843366'

# Group Dự phòng
- name: systems-team-telegram
  webhook_configs:
  - url: 'http://bravo-monitoring-alertbot.bravo-monitoring.svc.cluster.local:9087/alert/-4194274582'

route:
  continue: false
  group_by: ['instance']
  group_interval: 1m
  group_wait: 5s
  repeat_interval: 1m
  receiver: systems-team-telegram
  routes:

##################### SERVER-NODE EXPORTER #######################
    # Node
    - match:
        app_type: Cluster Manager
        category: server  
      receiver: system-kubernetes
      group_wait: 10s
    # RAM
    - match:
        app_type: Cluster Manager
        category: memory  
      receiver: system-kubernetes
      group_wait: 10s
    # DISK
    - match:
        app_type: Cluster Manager
        category: disk  
      receiver: system-kubernetes
      group_wait: 10s
    # CPU
    - match:
        app_type: Cluster Manager
        category: cpu  
      receiver: system-kubernetes
      group_wait: 10s

#######
    # Node
    - match:
        app_type: Cluster Application
        category: server  
      receiver: system-kubernetes
      group_wait: 10s
    # RAM
    - match:
        app_type: Cluster Application
        category: memory  
      receiver: system-kubernetes
      group_wait: 10s
    # DISK
    - match:
        app_type: Cluster Application
        category: disk  
      receiver: system-kubernetes
      group_wait: 10s
    # CPU
    - match:
        app_type: Cluster Application
        category: cpu  
      receiver: system-kubernetes
      group_wait: 10s

##################### KUBERNETES #######################
    - match:
        app_type: Cluster Application
        category: kubernetes  
      receiver: service-kubernetes
      group_wait: 10s

    - match:
        app_type: Cluster Manager
        category: kubernetes  
      receiver: service-kubernetes
      group_wait: 10s