global:
  resolve_timeout: 1m

receivers:

# Group Dự phòng
- name: systems-team-telegram
  webhook_configs:
  - url: 'http://bravo-monitoring-alertbot.bravo-monitoring.svc.cluster.local:9087/alert/-4570531790'

- name: cluster-kubernetes
  webhook_configs:
  - url: 'http://bravo-monitoring-alertbot2.bravo-monitoring.svc.cluster.local:9087/alert/-4579843366'

route:
  continue: false
  group_by: ['instance']
  group_interval: 1m
  group_wait: 5s
  repeat_interval: 1m
  receiver: systems-team-telegram
  routes:

##################### SERVER-NODE EXPORTER #######################
    # Node
    - match:
        app_type: Cluster Manager
        category: server  
      receiver: systems-team-telegram
      group_wait: 10s
    # RAM
    - match:
        app_type: Cluster Manager
        category: memory  
      receiver: systems-team-telegram
      group_wait: 10s
    # DISK
    - match:
        app_type: Cluster Manager
        category: disk  
      receiver: systems-team-telegram
      group_wait: 10s
    # CPU
    - match:
        app_type: Cluster Manager
        category: cpu  
      receiver: systems-team-telegram
      group_wait: 10s
    # KUBERNETES
    - match:
        app_type: Cluster Manager
        category: kubernetes  
      receiver: cluster-kubernetes
      group_wait: 10s