apiVersion: v2
name: prometheus-grafana-helmchart
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: grafana
    version: "6.17.5"
    repository: "https://grafana.github.io/helm-charts"
