apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    app: {{ include "prometheus.name" . }}
data:
  prometheus.yml: |-
    {{ .Files.Get "config/rules/config.yml" | nindent 4 }} 

  k8s-clustermanager.yml: |-
    {{ .Files.Get "config/rules/k8s-clustermanager.yml" | nindent 4 }}

  k8s-application.yml: |-
    {{ .Files.Get "config/rules/k8s-application.yml" | nindent 4 }} 


