apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    app: {{ include "prometheus.name" . }}
data:
  prometheus.yml: |-
    {{ tpl .Values.prometheus.configTemplate . | nindent 4 }}

  kubernetes.yml: |-
    {{ tpl .Values.alertrule.ruleFile . | nindent 4 }}