apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    app: {{ include "prometheus.name" . }}
data:
  prometheus.yml: |-
    {{ .Files.Get "config/rules/config.yml" | nindent 4 }} 

  kubernetes.yml: |-
    {{ .Files.Get "config/rules/kubernetes.yml" | nindent 4 }} 


