apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "prometheus.fullname" . }}-gateway
  namespace: bravo-monitoring
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "m-prometheus.bravo.com.vn"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "prometheus.fullname" . }}-virtual-service
  namespace: bravo-monitoring
spec:
  hosts:
    - "m-prometheus.bravo.com.vn"
  gateways:
    - {{ include "prometheus.fullname" . }}-gateway
  http:
    - route:
        - destination:
            host: {{ include "prometheus.fullname" . }}
            port:
              number:  9090
