apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  labels:
    app: prometheus
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9090
  selector:
    app: prometheus
  type: {{ .Values.service.type }}
