replicaCount: 1

image:
  repository: prom/prometheus
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: prometheus.local
      paths: ["/"]
  tls: []

persistence:
  enabled: true
  size: 10Gi
  storageClassName: nfs-csi-synology

prometheus:
  config:
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.metrics-system.svc.cluster.local:8080']  

secret:
  enabled: true
  adminPassword: "admin"
