replicaCount: 1

image:
  repository: prom/prometheus
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: prometheus.local
      paths: ["/"]
  tls: []

persistence:
  enabled: true
  size: 10Gi
  storageClassName: nfs-csi-synology


# Config lấy thông tin dữ liệu
prometheus:
  configTemplate: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'kubernetes-managerment-cluster'
        metrics_path: /metrics
        static_configs:
          - targets:
              - 'kube-state-metrics.metrics-system.svc.cluster.local:8080'
              - 'node-exporter-prometheus-node-exporter.metrics-system.svc.cluster.local:9100'
