replicaCount: 1

image:
  repository: prom/prometheus
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9090

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: prometheus.local
      paths: ["/"]
  tls: []

persistence:
  enabled: true
  size: 80Gi
  storageClassName: nfs-csi-gluster

prometheus:
  configTemplate: |-
    global:
      evaluation_interval: 1m
      scrape_interval: 15s
      scrape_timeout: 10s
      
    scrape_configs:

      - job_name: 'cluster-manager-k8s'
        scrape_timeout: 15s
        metrics_path: '/federate'
        scheme: http
        params:
          'match[]':
            - '{__name__=~".+"}'
        tls_config:
          # Skip SSL verification
          insecure_skip_verify: true
        static_configs:
          - targets: [172.16.19.8:31419]
            labels:
              cluster_name: cluster-manager-k8s

      - job_name: 'cluster-application-k8s'
        scrape_timeout: 15s
        metrics_path: '/federate'
        scheme: http
        params:
          'match[]':
            - '{__name__=~".+"}'
        tls_config:
          # Skip SSL verification
          insecure_skip_verify: true
        static_configs:
          - targets: [172.16.19.18:32645]
            labels:
              cluster_name: cluster-application-k8s


      - job_name: 'k8s-management-node'
        metrics_path: /metrics
        static_configs:
          - targets:
              - '172.16.19.7:9100'
              - '172.16.19.8:9100'
              - '172.16.19.9:9100'
              - '172.16.19.11:9100'
              - '172.16.19.12:9100'
              - '172.16.19.13:9100'
          
      - job_name: 'k8s-bravoapp-node'
        metrics_path: /metrics
        static_configs:
          - targets:
              - '172.16.19.17:30749'
              - '172.16.19.17:9100'
              - '172.16.19.18:9100'
              - '172.16.19.19:9100'
              - '172.16.19.21:9100'
              - '172.16.19.22:9100'
              - '172.16.19.23:9100'
              - '172.16.19.24:9100'
              - '172.16.19.25:9100'