replicaCount: 1

image:
  repository: prom/prometheus
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9090

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: prometheus.local
      paths: ["/"]
  tls: []

persistence:
  enabled: true
  size: 10Gi
  storageClassName: nfs-csi-synology

resources: {}

secret:
  enabled: true
  adminPassword: "admin"
