replicaCount: 1

image:
  repository: prom/prometheus
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9090

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: prometheus.local
      paths: ["/"]
  tls: []

persistence:
  enabled: true
  size: 80Gi
  storageClassName: nfs-csi-nas


prometheus:
  configTemplate: |-
    global:
      evaluation_interval: 1m
      scrape_interval: 15s
      scrape_timeout: 10s

    # Rules config 
    rule_files:
      - "/etc/prometheus/rules/kubernetes.yml"
    
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets: ['bravo-monitoring-alertmanager.bravo-monitoring.svc.cluster.local:9093']

    scrape_configs:
      - job_name: 'cluster-manager-k8s'
        scrape_timeout: 15s
        metrics_path: '/federate'
        scheme: http
        params:
          'match[]':
            - '{__name__=~".+"}'
        tls_config:
          # Skip SSL verification
          insecure_skip_verify: true
        static_configs:
          - targets: [192.168.140.208:32083]
            labels:
              cluster_name: cluster-manager-k8s

      - job_name: 'cluster-application-k8s'
        scrape_timeout: 15s
        metrics_path: '/federate'
        scheme: http
        params:
          'match[]':
            - '{__name__=~".+"}'
        tls_config:
          # Skip SSL verification
          insecure_skip_verify: true
        static_configs:
          - targets: [192.168.140.18:32645]
            labels:
              cluster_name: cluster-application-k8s


      - job_name: 'k8s-management-node'
        metrics_path: /metrics
        static_configs:
          - targets:
              - '192.168.140.207:9100'
              - '192.168.140.208:9100'
              - '192.168.140.209:9100'
              - '192.168.140.211:9100'
              - '192.168.140.212:9100'
              - '192.168.140.213:9100'
          
      - job_name: 'k8s-bravoapp-node'
        metrics_path: /metrics
        static_configs:
          - targets:
              # - '192.168.140.17:30749'
              - '192.168.140.217:9100'
              #- '192.168.140.218:9100'
              - '192.168.140.219:9100'
              - '192.168.140.221:9100'
              - '192.168.140.222:9100'
              - '192.168.140.223:9100'
