replicaCount: 1

image:
  repository: prom/prometheus
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9090

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: prometheus.local
      paths: ["/"]
  tls: []

persistence:
  enabled: true
  size: 10Gi
  storageClassName: nfs-csi-synology


# Config lấy thông tin dữ liệu
prometheus:
  configTemplate: |-
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'k8s-managerment-cluster'
        metrics_path: /metrics
        static_configs:
          - targets:
              - 'kube-state-metrics.metrics-system.svc.cluster.local:8080'
              - '192.168.3.7:9100'
              - '192.168.3.8:9100'
              - '192.168.3.9:9100'
              - '192.168.3.11:9100'
              - '192.168.3.12:9100'
              - '192.168.3.13:9100'
      - job_name: 'k8s-bravoapp-cluster'
        metrics_path: /metrics
        static_configs:
          - targets:
              - '192.168.3.17:30808'
              - '192.168.3.17:9100'
              - '192.168.3.18:9100'
              - '192.168.3.19:9100'
              - '192.168.3.21:9100'
              - '192.168.3.22:9100'
              - '192.168.3.23:9100'