replicaCount: 1

image:
  repository: prom/prometheus
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 9090

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: prometheus.local
      paths: ["/"]
  tls: []

persistence:
  enabled: true
  size: 10Gi
  storageClassName: nfs-csi-synology

prometheus:
  configTemplate: |-
    global:
      evaluation_interval: 1m
      scrape_interval: 15s
      scrape_timeout: 10s
      
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
              - localhost:9090

      - job_name: kubernetes-apiservers
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        static_configs:
          - targets:
              - 192.168.3.10:6443
        relabel_configs:
          - action: keep
            regex: default;kubernetes;https
            source_labels:
              - __meta_kubernetes_namespace
              - __meta_kubernetes_service_name
              - __meta_kubernetes_endpoint_port_name
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          insecure_skip_verify: true
          

      - job_name: 'k8s-management-cluster'
        metrics_path: /metrics
        static_configs:
          - targets:
              - 'bravo-k8s-kube-state-metrics.bravo-metrics.svc.cluster.local:8080'
              - '192.168.140.7:9100'
              - '192.168.140.8:9100'
              - '192.168.140.9:9100'
              - '192.168.140.11:9100'
              - '192.168.140.12:9100'
              - '192.168.140.13:9100'
          
      - job_name: 'k8s-bravoapp-cluster'
        metrics_path: /metrics
        static_configs:
          - targets:
              - '192.168.140.17:30808'
              - '192.168.140.17:9100'
              - '192.168.140.18:9100'
              - '192.168.140.19:9100'
              - '192.168.140.21:9100'
              - '192.168.140.22:9100'
              - '192.168.140.23:9100'
