apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-config
  labels:
    app: {{ include "grafana.name" . }}
data:
  grafana.ini: |-
    {{- with .Values.grafana.ini }}
    {{- range $section, $settings := . }}
    [{{ $section }}]
    {{- range $key, $value := $settings }}
    {{ $key }} = {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- end }}
