apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  labels:
    app: {{ include "grafana.name" . }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "grafana.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "grafana.name" . }}
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: admin-password
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            seccompProfile:
              type: RuntimeDefault                  
          volumeMounts:
            - name: grafana-storage
              mountPath: {{ .Values.persistence.mountPath }}
            - name: grafana-logs
              mountPath: {{ .Values.persistence.logsPath }}
            - name: grafana-config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsNonRoot: true
        runAsUser: 472
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-pvc
        - name: grafana-logs
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-logs-pvc
        - name: grafana-config
          configMap:
            name: {{ include "grafana.fullname" . }}-config
