apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "grafana.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    alb.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  rules:
  - host: m-grafana.bravo.com.vn
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ include "grafana.fullname" . }}
            port:
              number: 80
