apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grafana.fullname" . }}-pvc
  labels:
    app: {{ include "grafana.name" . }}
spec:
  accessModes:
    - {{ .Values.persistence.accessModes | join ", " }}
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "grafana.fullname" . }}-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.logSize }}
