apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-secret
  labels:
    app: {{ include "grafana.name" . }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser | b64enc | quote }}
  admin-password: {{ .Values.adminUser | b64enc | quote }}