replicaCount: 1

image:
  repository: grafana/grafana
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

persistence:
  enabled: true
  accessModes:
    - ReadWriteMany
  size: 10Gi
  logSize: 2Gi
  storageClassName: nfs-csi-synology
  mountPath: /var/lib/grafana
  logsPath: /var/log/grafana

adminUser: admin

# Grafana Config
grafana:
  ini:
    analytics:
      check_for_updates: false
    server:
      root_url: https://m-grafana.bravo.com.vn/
      serve_from_sub_path: true
    users:
      default_theme: dark
    auth:
      disable_login_form: false
    security:
      allow_embedding: true
    paths:
      data: /var/lib/grafana/
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    auth.anonymous:
      enabled: true