groups:
  - name: Rules
    rules:
      # Node Down
      - alert: Cảnh Báo Server
        expr:  up{instance=~".+",job="k8s-management-node"} == 0
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Cluster Manager
          category: server
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Service giám sát hoặc server bị tắt trên máy chủ {{ $labels.instance }}"
          description: | 
                Vui lòng kiểm tra lại !