groups:
  - name: Rules
    rules:
      # Node Down
      - alert: Cảnh Báo Server
        expr:  up{instance=~".+",job="k8s-bravoapp-node"} == 0
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Cluster Application
          category: server
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Service giám sát hoặc server bị tắt trên máy chủ {{ $labels.instance }}"
          description: | 
                Vui lòng kiểm tra lại !

      # Ram Rules
      - alert: Cảnh báo RAM
        expr: (node_memory_MemTotal_bytes{job="k8s-bravoapp-node", instance=~".+"} - node_memory_MemFree_bytes{job="k8s-bravoapp-node", instance=~".+"} - node_memory_Buffers_bytes{job="k8s-bravoapp-node", instance=~".+"} - node_memory_Cached_bytes{job="k8s-bravoapp-node", instance=~".+"} ) / (node_memory_MemTotal_bytes{job="k8s-bravoapp-node", instance=~".+"}) * 100 > 95
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Cluster Application
          category: memory
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "RAM Server > 95%"
          description: |
            
            RAM đã sử dụng chiếm {{ printf "%.2f" $value }}% / 100%

            Thông Tin Cụ Thể:

                 * TOTAL RAM: {{ query (printf "node_memory_MemTotal_bytes{job='k8s-bravoapp-node', instance=~'%s'}" $labels.instance) | first | value  | humanize1024}}

                 * Ram sử dụng: {{ query (printf "node_memory_MemTotal_bytes{job='k8s-bravoapp-node', instance=~'%s'} - node_memory_MemFree_bytes{job='k8s-bravoapp-node', instance=~'%s'} - node_memory_Cached_bytes{job='k8s-bravoapp-node', instance=~'%s'} - node_memory_Buffers_bytes{job='k8s-bravoapp-node', instance=~'%s'}" $labels.instance $labels.instance $labels.instance $labels.instance) | first | value | humanize1024 }}
                                   
                 * Ram Cache/buffe: {{ query (printf "node_memory_Cached_bytes{job='k8s-bravoapp-node', instance=~'%s'} + node_memory_Buffers_bytes{job='k8s-bravoapp-node', instance=~'%s'}" $labels.instance $labels.instance) | first | value  | humanize1024}}

                 * Ram còn lại:  {{ query (printf "node_memory_MemFree_bytes{job='k8s-bravoapp-node', instance=~'%s'}" $labels.instance) | first | value | humanize1024 }}

      # CPU Rules
      - alert: Cảnh Báo CPU
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{job="k8s-bravoapp-node", instance=~".+",mode="idle"}[1m])) * 100) > 90
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Cluster Application
          category: cpu
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "CPU Server > 95%"
          description: | 
            CPU sử dụng đạt tới  {{ printf "%.2f" $value }}% / 100%


      # Disk Rules
      - alert: Cảnh Báo Phân Vùng Ổ Cứng
        expr: (100 - ((node_filesystem_free_bytes{instance=~".+",job="k8s-bravoapp-node",mountpoint=~".+",fstype!~"tmpfs|aufs|overlay|vfat|ramfs"}) / (node_filesystem_size_bytes{instance=~".+",job="k8s-bravoapp-node",mountpoint=~".+",fstype!~"tmpfs|aufs|overlay|vfat|ramfs"}))* 100) > 90
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Cluster Application
          category: disk
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Ổ CỨNG SẮP ĐẦY"
          description: | 
          
              Phân vùng {{ $labels.device }} 
              Mount thư mục:  {{ $labels.mountpoint }} 
              Đạt ngưỡng {{ printf "%.2f" $value }}% / 100%

              Thông Tin Cụ Thể:
                * Dung lượng còn lại:  {{ query (printf "node_filesystem_free_bytes{job='k8s-bravoapp-node', instance=~'%s', mountpoint=~'%s' ,fstype!~'tmpfs|aufs|overlay|vfat|ramfs'}" $labels.instance $labels.mountpoint) | first | value | humanize1024}}


########################

      # Kuber API Server
      - alert: Cảnh Báo POD Kubeapi-server
        expr: up{exported_job="kubernetes-apiservers",job="cluster-application-k8s",instance=~".+"} == 0
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: Cluster Application
          category: kubernetes
          instance: "{{ $labels.exported_instance }}"
        annotations:
          summary: "Service Kubeapi-server {{ $labels.exported_instance }} bị tắt"
          description: | 
                Vui lòng kiểm tra lại !            