groups:
  - name: Rules
    rules:
      # Node Down
      - alert: Cảnh Báo Server
        expr:  up{instance=~".+"} == 0
        for: 1m
        labels:
          severity: Khẩn cấp
          app_type: ClusterManager
          category: server
          instance: "{{ $labels.instance }}"
        annotations:
          summary: "Node-export trên server {{ $labels.instance }} bị tắt"
          description: | 
                Vui lòng kiểm tra lại service giám sát trên server, kiểm lại VPN site to site hoặc kiểm tra server có bị tắt hay không ?